In [1]:
import numpy as np

a=np.matrix([[1,2,1],[2,1,-1],[2,-1,2]])
b=np.matrix([[9],[3],[-4]])


print("\n\n", a)

def fatoraLU(A,b):
    U=np.copy(A)#Faz uma copia da matriz a
    n=np.shape(U)[0]
    L=np.eye(n)#cria uma matriz identidade L
    print(L)
    print("\n\n")
    for j in np.arange(n-1):
        for i in np.arange(j+1,n):
            L[i,j]=U[i,j]/U[j,j]
            for k in np.arange(j+1,n):
                U[i,k]=U[i,k]-L[i,j]*U[j,k]
            U[i,j]=0
            b[j,0]=b[j,0]-L[j,i]*b[i,0]
    return L, U, b

def solucaoDoSistema(A,b):
    L = fatoraLU(A,b)[0]
    U = fatoraLU(A,b)[1]
    R = fatoraLU(A,b)[2]
    
    y = np.zeros((A.shape[0],1))    
    y[0,0] = R[0,0]/L[0,0]    
    for i in range(1, A.shape[0]):
        s = 0
        for j in range(0,i):
            s = s + L[j,i]*y[j,0]
            y[i,0] = (R[i,0] - s)/L[i,i]
    
    x = np.zeros((A.shape[0],1))
    x[A.shape[0]-1,0] = y[A.shape[0]-1,0]/U[A.shape[0]-1,A.shape[0]-1]
    for i in range(A.shape[0]-1,-1,-1):
        s = 0
        for j in range(i+1,A.shape[0]):
            s = s + U[i,j]*x[j,0]
            x[i,0] = (y[i,0] - s)/U[i,i]
    
    return y,x

F = np.matrix([[3.,2.,4.],[1.,1.,2.],[4.,3.,2.]])
G = np.matrix([[1.],[2.],[3.]])
print("Ly = b.\n y = \n", solucaoDoSistema(F,G)[0])
print("\nUx = y.\n x = \n", solucaoDoSistema(F,G)[1])




print(fatoraLU(a,b))
print(solucao(a,b,3))



 [[ 1  2  1]
 [ 2  1 -1]
 [ 2 -1  2]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



Ly = b.
 y = 
 [[ 1.]
 [ 2.]
 [ 3.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]




Ux = y.
 x = 
 [[-3.66666667]
 [ 7.5       ]
 [-0.75      ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



(array([[ 1.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ],
       [ 2.        ,  1.66666667,  1.        ]]), array([[ 1,  2,  1],
       [ 0, -3, -3],
       [ 0,  0,  5]]), matrix([[ 9],
        [ 3],
        [-4]]))


NameError: name 'solucao' is not defined